### ISSUE TITLE
Tried to install on localhost

### ISSUE THREAD

**Issue by ishendyweb** [applicationsdev/eCommerce-Nodejs-MongoDB#1]
I would like a guide on how to setup the package and get it running on localhost.

**Comment by qomi210** [comment]
hi
i wanna use this in local but after installing package  and running npm start , app crashed in below errors:

internal/modules/cjs/loader.js:573
    throw err;
    ^

Error: Cannot find module './config/app'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (D:\IT-work\pv-projects\12.dotstart.ir\new.start\dotstart2\eCommerce-Nodejs-MongoDB-master\server.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)

tnx for guiding
